### ISSUE TITLE
Umbrella issue for dockerizing the server

### ISSUE THREAD

**Issue by alivenotions** [upaytech/as-server#3]
- [x] Create docker config for Express web server (resolved by 03db077e26b7d5067bb2e8ba1cfd349c6540d330)
- [ ] Create docker config for Postgres instance and seed it with dummy data for development
- [x] Create a docker-compose file for working on dev (resolved by 436c0bf495d757ee03c5fe16613b9dabba96eb5c)
- [ ] Create a pipeline for prod
